adapter.1.17=com.vzoom.range.fabric.modern.v117
adapter.1.17.1=com.vzoom.range.fabric.modern.v117
adapter.1.18=com.vzoom.range.fabric.modern.v117
adapter.1.18.1=com.vzoom.range.fabric.modern.v117
adapter.1.18.2=com.vzoom.range.fabric.modern.v117
adapter.1.19=com.vzoom.range.fabric.modern.v119
adapter.1.19.1=com.vzoom.range.fabric.modern.v119
adapter.1.19.2=com.vzoom.range.fabric.modern.v119
adapter.1.19.3=com.vzoom.range.fabric.modern.v1193
adapter.1.19.4=com.vzoom.range.fabric.modern.v1193
adapter.1.20=com.vzoom.range.fabric.modern.v120
adapter.1.20.1=com.vzoom.range.fabric.modern.v120
adapter.1.20.2=com.vzoom.range.fabric.modern.v1202
adapter.1.20.3=com.vzoom.range.fabric.modern.v1202
adapter.1.20.4=com.vzoom.range.fabric.modern.v1202
adapter.1.20.5=com.vzoom.range.fabric.modern.v1202
adapter.1.20.6=com.vzoom.range.fabric.modern.v1202
