pluginManagement {
    repositories {
        maven { url = "https://maven.fabricmc.net" }
        mavenCentral()
        gradlePluginPortal()
        maven { url = "https://maven.terraformersmc.com/releases" }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

rootProject.name = "vZoom"

include(":core")
include(":versions:fabric-1_14")
include(":versions:fabric-1_15")
include(":versions:fabric-1_16")
include(":versions:fabric-1_16_1")
include(":versions:fabric-1_17")
include(":versions:fabric-1_19")
include(":versions:fabric-1_19_3")
include(":versions:fabric-1_20")
include(":versions:fabric-1_20_2")
include(":versions:fabric-1_21")
include(":versions:fabric-1_21_2")
include(":versions:fabric-1_21_6")
include(":versions:fabric-1_21_9")
include(":versions:fabric-1_21_11")
include(":versions:fabric-26_1")
include(":versions:fabric-26_2")
include(":versions:fabric-26_3")
include(":versions:neoforge-1_20_5")
include(":versions:neoforge-1_21")
include(":versions:neoforge-1_21_2")
include(":versions:neoforge-1_21_6")
include(":versions:neoforge-1_21_9")
include(":versions:neoforge-1_21_11")
include(":versions:neoforge-26_1")
include(":versions:neoforge-26_2")
include(":versions:neoforge-26_3")
include(":ranges:fabric-legacy")
include(":ranges:fabric-modern")
include(":ranges:fabric-current")
include(":ranges:fabric-26")
include(":ranges:neoforge-legacy")
include(":ranges:neoforge-current")
include(":ranges:neoforge-26")
