adapter.26.1=com.vzoom.range.fabric.twentysix.v261
adapter.26.1.1=com.vzoom.range.fabric.twentysix.v261
adapter.26.1.2=com.vzoom.range.fabric.twentysix.v261
adapter.26.2=com.vzoom.range.fabric.twentysix.v262
adapter.26.3=com.vzoom.range.fabric.twentysix.v263
