/*
 * Copyright 2026 CallMeAlphabet (ItzAlphabet)
 * Copyright 2026 Vextoly
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.17-SNAPSHOT'
}

base { archivesName = "vzoom-v1_21_11" }

loom {
    mods {
        "vzoom" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.findProperty('mc_v1_21_11')}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${rootProject.findProperty('loader_v1_21_11')}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.findProperty('fapi_v1_21_11')}"
    modCompileOnlyApi "com.terraformersmc:modmenu:${rootProject.findProperty('modmenu_v1_21_11')}"
    implementation project(':core')
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") { expand "version": project.version }
}

int jv = Integer.parseInt(rootProject.findProperty('java_v1_21_11').toString())

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = jv
}

configurations.configureEach {
    attributes.attribute(org.gradle.api.attributes.java.TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, jv)
}

jar {
    from(project(':core').sourceSets.main.output)
}

java {
    sourceCompatibility = JavaVersion.toVersion(jv)
    targetCompatibility = JavaVersion.toVersion(jv)
}
