modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"
issueTrackerURL="https://github.com/CallMeAlphabet/vZoom/issues"

[[mods]]
modId="vzoom"
version="${version}"
displayName="vZoom"
authors="Vextoly, ItzAlphabet"
displayURL="https://github.com/CallMeAlphabet/vZoom"
logoFile="logo.png"
description='''Infinite, smooth cinematic zoom. Hold the zoom key (default C) and scroll the mouse wheel to adjust the zoom depth with no fixed limits.'''

[[mixins]]
config="vzoom-v1205.mixins.json"

[[mixins]]
config="vzoom-v121.mixins.json"

[[mixins]]
config="vzoom-v1212.mixins.json"

[[mixins]]
config="vzoom-v1216.mixins.json"

[[mixins]]
config="vzoom-v1219.mixins.json"

[[mixins]]
config="vzoom-v12111.mixins.json"

[[dependencies.vzoom]]
modId="neoforge"
type="required"
versionRange="[20.5.21-beta,22)"
ordering="NONE"
side="BOTH"

[[dependencies.vzoom]]
modId="minecraft"
type="required"
versionRange="[1.20.5,1.21.12)"
ordering="NONE"
side="BOTH"
