adapter.1.20.5=com.vzoom.range.neoforge.current.v1205
adapter.1.20.6=com.vzoom.range.neoforge.current.v1205
adapter.1.21=com.vzoom.range.neoforge.current.v121
adapter.1.21.1=com.vzoom.range.neoforge.current.v121
adapter.1.21.2=com.vzoom.range.neoforge.current.v1212
adapter.1.21.3=com.vzoom.range.neoforge.current.v1212
adapter.1.21.4=com.vzoom.range.neoforge.current.v1212
adapter.1.21.5=com.vzoom.range.neoforge.current.v1212
adapter.1.21.6=com.vzoom.range.neoforge.current.v1216
adapter.1.21.7=com.vzoom.range.neoforge.current.v1216
adapter.1.21.8=com.vzoom.range.neoforge.current.v1216
adapter.1.21.9=com.vzoom.range.neoforge.current.v1219
adapter.1.21.10=com.vzoom.range.neoforge.current.v1219
adapter.1.21.11=com.vzoom.range.neoforge.current.v12111
