adapter.1.14=com.vzoom.range.fabric.legacy.v114
adapter.1.14.1=com.vzoom.range.fabric.legacy.v114
adapter.1.14.2=com.vzoom.range.fabric.legacy.v114
adapter.1.14.3=com.vzoom.range.fabric.legacy.v114
adapter.1.14.4=com.vzoom.range.fabric.legacy.v114
adapter.1.15=com.vzoom.range.fabric.legacy.v115
adapter.1.15.1=com.vzoom.range.fabric.legacy.v115
adapter.1.15.2=com.vzoom.range.fabric.legacy.v115
adapter.1.16=com.vzoom.range.fabric.legacy.v116
adapter.1.16.1=com.vzoom.range.fabric.legacy.v1161
adapter.1.16.2=com.vzoom.range.fabric.legacy.v1161
adapter.1.16.3=com.vzoom.range.fabric.legacy.v1161
adapter.1.16.4=com.vzoom.range.fabric.legacy.v1161
adapter.1.16.5=com.vzoom.range.fabric.legacy.v1161
