modLoader="javafml"
loaderVersion="[4,)"
license="Apache-2.0"

[[mods]]
modId="vzoom"
version="${version}"
displayName="vZoom"
authors="Vextoly, ItzAlphabet"
description='''Infinite, smooth cinematic zoom. Hold the zoom key (default C) and scroll the mouse wheel to adjust the zoom depth with no fixed limits.'''

[[mixins]]
config="vzoom.mixins.json"

[[dependencies.vzoom]]
    modId="neoforge"
    type="required"
    versionRange="[21.9.16-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vzoom]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.9]"
    ordering="NONE"
    side="BOTH"
